# Generated by Django 5.2 on 2025-11-10 19:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='impuestos',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='descuento_item',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='notas',
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total'),
        ),
    ]
